### ISSUE TITLE
Site matching doesn't support multiple subdomains

### ISSUE THREAD

**Issue by jonathanernst** [ttyridal/masterpassword-chrome#12]
If you log in to site1.domain.com with masterpassword-chrome and want to use it to site2.domain.com, with a different password, the matching is always done on domain.com (although the calculation is done on the manually entered site1.domain.com (and/or site2.domain.com if you add it)).

Changing in the site settings domain.com by site1.domain.com in the (matching) field doesn't work.

**Comment by ttyridal** [comment]
Thanks.  You're right.. Seems it will only match the two last parts of the url (three for some hard coded ones like .co.uk)..

It would be better if the complete match field (as shown in configuration page) is used.

**Comment by jmorgannz** [comment]
This is a real pain for basically any country other than the USA.  
Other countries use two-level domains like *.gov.nz or *.org.nz or *.net.nz  

Is there any chance of this being turned into a config page rather than hard-coded as it is right now?  
I'd happily fork and make the change - it's having to jump through the hoops to get the fork accepted to chrome store, or having to manually sideload a 'dev mode' extension that puts me off doing it.

**Comment by ttyridal** [comment]
Hi, I'm happy to announce that a fix for this is in the making :)  

issues is the same as ttyridal/masterpassword-firefox#52

I'm merging the two projects and have implemented this for the upcoming release.

**Comment by jmorgannz** [comment]
@ttyridal doh. sure wish I'd received that reply 4 hours ago (re my other pull request!)

**Comment by ttyridal** [comment]
fixed and released
